Fix advanced settings
hamburger-software/ansible-role-vmware_ubuntu_cloud_image pull request #5
Opened 2021-12-10 03:36 UTC by dotalchemy

Fixed a thing introduced by a change made to the 'community.vmware' collection where `customsettings` was replaced with `advanced_settings` in a recent release of the collection.

This caused the role to fail with `Unable to find custom value key disk.EnableUUID` 

See [Github Issue #179](https://github.com/ansible-collections/community.vmware/pull/179)
See [vmware_guest_module](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html)

Tested on whatever version of Ansible is in the very latest AWX Operator build, but there shouldn't be a version dependency change as it's just a string edit in the yaml to match what `community.vmware` is expecting.

2021-12-12 09:26 UTC, albers commented
Thanks very much for your contribution.
I will need some time to review it because I first need to set up suitable testing environments.

2021-12-14 17:14 UTC, albers requested changes
I did some research:

`advanced_settings` was added to *vmware_guest* in the [1.8.0 release](https://github.com/ansible-collections/community.vmware/blob/main/CHANGELOG.rst#v1-8-0) of the _community.vmware collection_.
This release is part of the Ansible community package 3.2.0, which is based on ansible-core 2.10.7 (see [build data](https://github.com/ansible-community/ansible-build-data/blob/main/3/CHANGELOG-v3.rst#ansible-base-4)).

Because this change is a breaking one, `min_ansible_version` will have to be changed to 2.10.7 [here](https://github.com/hamburger-software/ansible-role-vmware_ubuntu_cloud_image/blob/97d8908ec75544781ec87a55c2b8999315da4a8b/meta/main.yml#L7).

Please also change the [requirements section](https://github.com/hamburger-software/ansible-role-vmware_ubuntu_cloud_image/blob/97d8908ec75544781ec87a55c2b8999315da4a8b/README.md?plain=1#L45) to
"The minimum *community.vmware collection* version is 1.8.0, which is part of the Ansible community package 3.2.0."

2021-12-14 17:14 UTC, albers commented on README.md
> +- Optionally sets VM notes and/or VM [Configuration Parameters](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.html.hostclient.doc/GUID-8C639077-FF16-4D5D-9A7A-E16902CE00C2.html).
Please change the link to use the 7.0 documentation.

2021-12-14 17:14 UTC, albers commented on tasks/main.yml
> -    customvalues: "{{ customvalues | default(omit) }}"
An alternative to replacing `customvalues` with `advanced_settings` could be to add the new option and leave the `customvalues` in place.  After all, this option still exists, and maybe there are other use cases of `customvalues` than the one documented in the module.

We could increase portability this way. WDYT?

2021-12-16 18:22 UTC, dotalchemy commented on tasks/main.yml
> -    customvalues: "{{ customvalues | default(omit) }}"
Yep, you're 100% on this - will make the changes accordingly!

2021-12-22 04:35 UTC, dotalchemy reviewed
Please review and let me know if there are any changes you'd like to see!

2021-12-22 04:35 UTC, dotalchemy commented on tasks/main.yml
> -    customvalues: "{{ customvalues | default(omit) }}"
added `customvalues` back in and tested - they are set correctly according to the definition in the playbook, though custom value keys won't be created if they don't exist - they must exist in vCenter first in order to be assigned a value

2021-12-22 12:04 UTC, albers approved these changes
Perfect, thank you very much for the contribution.

2021-12-22 12:05 UTC, merged

2021-12-22 21:04 UTC, albers commented
@dotalchemy released [v6.0.0](https://github.com/hamburger-software/ansible-role-vmware_ubuntu_cloud_image/releases/tag/v6.0.0)